period: ""                                          # standard yaml file is located in:
pass: "default"                                     # AliPhysics/PWG/EMCAL/config/
CellEnergy:
    createHistos: true
    enabled: true                                   # Whether to enable the task
    enableNewTempCalib: false                       # ADDED !!
    enableShaperCorrection: true                    # ADDED !!
    enableLGDetermination: true                     # ONLY USE THIS FOR RUN1
CellBadChannel:
    enabled: true
    createHistos: true
    load1DBadChMap: true
CellTimeCalib:
    enabled: true                                   # Whether to enable the task
    createHistos: true                              # ADDED !!
    doCalibrateLowGain: true                        # ADDED !!
    doMergedBCs: true                               # ADDED !!
    doCalibMergedLG: false                          # ADDED !!
Clusterizer:
    enabled: true
    createHistos: false
    clusterizer: kClusterizerv3                     # faster version of v2
    cellE: 0.1
    seedE: 0.3
    cellTimeMin: -500e-9
    cellTimeMax: +500e-9
    clusterTimeLength: 1e6
    recalDistToBadChannels: true
    recalShowerShape: true
    load1DBadChMap: true
    remapMcAod: false
    diffEAggregation: 0.0
ClusterExotics:
    enabled: true                                   # Whether to enable the task
    createHistos: true                              # Whether the task should create outputhistograms
    fMaxFcross: 0.97                                # ADDED !!
    fHighEnergyNdiffCut: 50                         # ADDED !!
    fMinCellEnNdiffCut: 0                           # ADDED !!
ClusterNonLinearity:
    enabled: true                                   # Whether to enable the task
    setForceClusterE: true                          #for cluster energy to correct for non-linearity
    createHistos: true                              # Whether the task should create output histograms
    nonLinFunct: kTestBeamShaper
ClusterNonLinearityMCAfterburner:                   # MC Cluster additional non-linearity afterburner correction component - To be applied after the standard non-linearity correction
    enabled: false
ClusterTrackMatcher:                                # Cluster-track matcher component
    enabled: true
   #pt track cut in old version!
ClusterHadronicCorrection:                          # use no hadronic correction for g-h correlation
    enabled: true
    createHistos: true
    doMomDepMatching: true                          # This enables a momentum dependent eta/phi window for track matching
    hadCorr: 0.7                                    # Sets the fraction f of track p to subtract from matched cluster. To subtract all tracks within the eta-phi cut set hadCorr = 1+f. To subtract only one track set 0<hadCorr<1 where hadCorr=f.
    useM02SubtractionScheme: true                   # Flag to enable hadronic correction scheme using cluster M02 value. Must also use hadCorr>1 in order for this option to be enabled.
    useConstantSubtraction: true                    # Flag to perform constant rather than fractional subtraction in the case M02>0.4 with a matched track (only applicable if using M02 scheme). If false, uses the fraction f=hadCorr-1.
    constantSubtractionValue: 0.2356                # Value to be used for constant subtraction, in GeV (only applicable if using constant subtraction in M02 scheme).
